### ISSUE TITLE
 /host/azure.json path 

### ISSUE THREAD

**Issue by midebell** [Hexadite/acs-keyvault-agent#16]
How does /host/azure.json get set from /etc/kubernetes/azure.json ?

**Comment by idanlevin** [comment]
using a `hostPath` - 

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
...
spec:
  ...
    spec:
      containers:
      - ...
      initContainers:
        ...
        volumeMounts:
        - name: host-sp
          mountPath: /host/azure.json
          readOnly: true
        ...
    volumes:
      - name: host-sp
        hostPath:
          # this file contains the cluster service-principal, it exists on every node by default
          path: /etc/kubernetes/azure.json
          type: File
```
