### ISSUE TITLE
Support _SECRETS_DATA_KEY for kubernetes.io/tls

### ISSUE THREAD

**Issue by matthawley** [Hexadite/acs-keyvault-agent#32]
Would it be possible that when creating a kubernetes secret as `kubernetes.io/tls`, that it could support `_SECRETS_DATA_KEY`? We have a scenario where I'd like to have different secret names be created for conflicting certificates based on different keyvaults. Effectively, I'd like to have

```
env:
- name: SECRETS_KEYS
   value: ssl::ssl_cert.pem:ssl_key.pem
- name: SSL_SECRETS_DATA_KEY
  value: client-ssl
- name: CREATE_KUBERNETES_SECRETS
   value: "true"
- name: SECRETS_TYPE
   value: kubernetes.io/tls
```

to produce the `kubernetes.io/tls` secret named `client-ssl` rather than `ssl`.
